config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles, only: [:show, :new, :update, :edit, :create]
  root "items#index"
  resources :items do
   resources :comments, only: [:create]
   collection do
   get 'search'
   end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :item
  
  validates :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  with_options presence: true do
    validates :name
    validates :price
    validates :content
    validates :images
 end

 belongs_to          :user
 has_many_attached   :images
 has_many            :comments, dependent: :destroy

 def self.search(search)
  if search != ""
    Item.where('content LIKE(?)', "%#{search}%")
  else
    Item.all
  end
 end

 
end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user
  has_one_attached :image

  validates :name,   presence: true
  validates :detail, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :profile, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy

  delegate :name, :detail, :image, to: :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @item = Item.find(params[:item_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to item_path(@item)
    else
      @comments = @item.comments.includes(:user)
      render "items/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_item, only: [:edit, :update, :show, :destroy]

  def index
    @items = Item.all.order(created_at: :desc)
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to root_path, notice: "メニューが投稿されました"
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to root_path, notice: "メニューが更新されました"
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path, notice: "メニューが削除されました"
    else
      redirect_to root_path, notice: "メニューを削除できませんでした"
    end
  end

  def search
    @items = Item.search(params[:keyword])
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :content, images:[]).merge(user_id: current_user.id)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_action :find_profile, only: [:show, :update, :destroy, :edit]

  def show
  end

  def new
    return redirect_to edit_profile_path(current_user.profile) if current_user.profile.present?
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      redirect_to root_path, notice: "プロフィール登録が完了しました"
    else
      render :new
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to root_path, notice: "プロフィールを更新しました"
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :detail, :image)
  end

  def find_profile
    @profile = Profile.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/items/_item.html.erb
<div class="content-wrapper">
  <div class="content-block">
    <div class="content">
        <div class="user-about">
        <div class="image">
        <% if item.user.image.attached? %>
          <%= image_tag item.user.image %>
        <% else %>
          <%= image_tag "nouser.png"%>
        <% end %>
        </div> 

        <div class="profile">
            <div class="name-about">
              <div class="name">
                <%= item.user.name %>
              </div> 
            </div>
            
          <div class="detail">
            <%= item.user.detail %>
          </div>
        </div>
      </div>

        <% if item.images.attached? %>
         <div class="images">
         <% item.images.each do |image| %>
          <%= image_tag image %>
          <% end %>
         </div>
        <% end %>

        <div class="menu-name">
        <h2>[メニュー名]<%= item.name %></h2>
        </div>

        <div class="menu-price">
          <h2>[価格]<%= item.price %>円</h2>
          <% if user_signed_in? && item.user_id != current_user.id %>
           <h3><%= link_to '購入画面に進む', item_orders_path(@item), class:"item-red-btn" %></h3>
           <% end %>
        </div>

        <div class="text">
        <%= item.content %>
        </div>
        
        <div class="action-menu">
          <div class="comment">
            <% if user_signed_in? %>
          <%= form_with url: item_comments_path(item), model: @comment, data: { confirm: '誹謗中傷など、読む人が不快になるような内容は含まれていませんか？' }, local: true do |f| %>
            <div class="field"><br>
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: "button" %>
            </div>
          <% end %>
         <% end %>
        </div>
       </div>
     </div>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<div class="items-sell-main">
    <h1 class="items-sell-title">メニューの情報を更新</h1>
    <%= form_with model:@item, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="click-upload">
        <p>
          クリックして画像ファイルをアップロード
        </p>
        <%= f.file_field :images, multiple: true, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        メニュー名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          メニューの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :content, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
      </div>
      <div>
        <div class="price-content">
        <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        </span>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "投稿する", class: "button" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
 <% end %>
</div>

app/views/items/index.html.erb
<div class="content-wrapper">
  <div class="content-block">
    <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>  
   <% @items.each do |item| %>
    <div class="content">
      <div class="user-about">
        <div class="image">
          <% if item.user.image.attached? %>
           <%= image_tag item.user.image %>
          <% else %>
            <%= image_tag "nouser.png"%>
          <% end %>
        </div>
        <div class="profile">
          <div class="name-about">
            <div class="name">
               <%= item.user.name %>
            </div>
          </div>
          
          <div class="detail">
            <%= item.user.detail %>
          </div>
        </div>
      </div>
      <% if item.images.attached? %>
      <div class="images">
        <%= link_to item_path(item.id) do %>
          <% item.images.each do |image| %>
            <%= image_tag image %>
          <% end %>
          </div>
         <% end %>
        <% end %>
        <div class="text">
       <%= item.content %>
      </div>
    </div>
   <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="items-sell-main">
  <h1 class="items-sell-title">メニューの情報を入力</h1>
  <%= form_with model:@item, url: items_path, method: :post, local: true do |f| %>
    <%# <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="click-upload">
        <p>
          クリックして画像ファイルをアップロード
        </p>
        <%= f.file_field :images, multiple: true, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        メニュー名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          メニューの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :content, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
      </div>
      <div>
        <div class="price-content">
        <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        </span>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "投稿する", class: "button" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
 <% end %>
</div>

app/views/items/search.html.erb
<%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @items.each do |item| %>
     <%= render partial: "item", locals: { item: item } %>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="content-wrapper">
  <div class="content-block">
    <div class="content">
      <div class="user-about">
       <div class="image">
       <% if @item.user.image.attached? %>
        <%= image_tag @item.user.image %>
       <% else %>
        <%= image_tag "nouser.png"%>
       <% end %>
       </div> 

       <div class="profile">
          <div class="name-about">
            <div class="name">
              <%= @item.user.name %>
            </div> 
          </div>
          
        <div class="detail">
          <%= @item.user.detail %>
        </div>
      </div>
    </div>

        <% if @item.images.attached? %>
         <div class="images">
         <% @item.images.each do |image| %>
          <%= image_tag image %>
          <% end %>
         </div>
        <% end %>

        <div class="menu-name">
        <h2>[メニュー名]<%= @item.name %></h2>
        </div>
        
        <div class="menu-price">
          <h2>[価格]<%= @item.price %>円</h2>
          <% if user_signed_in? && @item.user_id != current_user.id %>
           <h3><%= link_to '購入画面に進む', item_orders_path(@item), class:"item-red-btn" %></h3>
           <% end %>
        </div>

       <div class="menu-price">    
        <% if user_signed_in? && current_user.id == @item.user_id %>
        <div class="item__manage">
          <%= link_to "編集する", edit_item_path(@item), class: :item__btn %>
          <%= link_to "削除する", item_path(@item), method: :delete, data: { confirm: '削除しますか？' }, class: :item__btn %>
        </div>
        <% end %>

        <div class="text">
        <%= @item.content %>
        </div>
        
        <div class="action-menu">
          <div class="comment">
            <% if user_signed_in? %>
          <%= form_with url: item_comments_path(@item), model: @comment, data: { confirm: '誹謗中傷など、読む人が不快になるような内容は含まれていませんか？' },　local: true do |f| %>
            <div class="field"><br>
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: "button" %>
            </div>
          <% end %>
         <% end %>
         <ol class="comments_lists">
            <% if @comments.present? %>
            <% @comments.each do |comment| %>
              <li class="comments_list">
                <%= comment.text %>
                <%= comment.user.name %>
                <%= comment.created_at %>
              <% end %>
              </li>
          <% end %>
         </ol>
       </div>
     </div>
   </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoumApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
    <%= render "shared/header" %>
    <%= render "shared/toast" %>
  <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with model: @profile, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, "ニックネーム" %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :detail, "お一言" %>
    <%= f.text_field :detail %>
  </div>

  <div class="form-group">
    <%= f.label :image, "プロフィール画像"%>
    <%= f.file_field :image %>
  </div>
    
    <div class="submit-block">
      <%= f.submit "作成する", class: "button" %>
    </div>
  <% end %>

app/views/profiles/edit.html.erb
<div>
  <h1>プロフィールを更新する</h1>
  <%= render 'form' %>
</div>

app/views/profiles/new.html.erb
<div>
  <h1>プロフィールを作成する</h1>
  <%= render 'form' %>
  
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
<p>©️2021 Youm!!!, All Rights reserved.</p>
</div>

app/views/shared/_header.html.erb
<div id="header">
  <div class="logo">
    <a href="/">Youm!!!<br>メニュー投稿アプリ</a>
  </div>

  

  <div class="link">
    <ul id="nav">
     <% if user_signed_in? %>
       <li>
          <%= link_to "メニュー投稿", new_item_path %>
        </li>
        <li>
         <%= link_to "プロフィール", new_profile_path %>
       </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_toast.html.erb
<% if flash[:notice].present? %>
<div class="toast">
  <div class="notice"><%= notice %></div>
</div>
<% end %>


<% if flash[:alert].present? %>
<div class="toast">
 <div class="alert"><%= alert %></div>
</div>
<% end %>